language: php

services:
  - mysql

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq postfix

before_script:
  # Mock mail service
  - sudo service postfix stop
  - smtp-sink -d "%d.%H.%M.%S" localhost:2500 1000 &
  - chmod +x tests/bin/fakesendmail.sh
  - sudo mkdir -p /var/qmail/bin
  - sudo cp tests/bin/fakesendmail.sh /var/qmail/bin/sendmail
  - sudo cp tests/bin/fakesendmail.sh /usr/sbin/sendmail
  - echo 'sendmail_path = "/usr/sbin/sendmail -t -i "' > $(php --ini|grep -m 1 "ini files in:"|cut -d ":" -f 2)/sendmail.ini

  # Prepare Filesystem
  - mkdir -p ./build
  - mkdir -p ./build/logs
  - mkdir -p ./build/clover
  - mkdir -p ./resource

  # Install PHP Libs
  - composer update-all

  # Install CMS
  - composer prepare-joomla
  - composer prepare-wordpress

script:
  - composer test

after_script:
  - composer coveralls

notifications:
  slack: jbzoo:lKYRTvAF36tRDfKTOK5zhFh9

