language: php

services:
  - mysql

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
  include:
    - php: 5.6
      env: XDEBUG_OFF="yes"
    - php: 7.0
      env: XDEBUG_OFF="yes"

before_install:
  # Mock mail services
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq postfix

before_script:
  # Disable xdebug PHP module
  - if [[ $XDEBUG_OFF = yes ]]; then phpenv config-rm xdebug.ini; fi;

  # Mock mail service
  - sudo service postfix stop
  - smtp-sink -d "%d.%H.%M.%S" 127.0.0.1:2500 1000 &
  - echo -e '#!/usr/bin/env bash\nexit 0' | sudo tee /usr/sbin/sendmail
  - echo 'sendmail_path = "/usr/sbin/sendmail -t -i "' | sudo tee "/home/travis/.phpenv/versions/`php -i | grep "PHP Version" | head -n 1 | grep -o -P '\d+\.\d+\.\d+.*'`/etc/conf.d/sendmail.ini"

  - composer self-update

script:
  - make
  - make server-joomla test-joomla
  - make server-wp test-wp
  - make validate phpmd phpcs phpcpd phploc

after_success:
  - make coveralls
