language: php

services:
  - mysql

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
  include:
    - php: 5.6
      env: XDEBUG_OFF="yes"
    - php: 7.0
      env: XDEBUG_OFF="yes"

before_install:
  - sudo make prepare-mail-install

before_script:
  # Disable xdebug PHP module
  - if [[ $XDEBUG_OFF = yes ]]; then phpenv config-rm xdebug.ini; fi;
  - sudo make prepare

script:
  - sudo make build
  - make test-all

after_script:
  - make coveralls
