language: php

services:
  - mysql

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
    - php: hhvm
  include:
    - php: 5.6
      env: XDEBUG_OFF="yes"
    - php: 7.0
      env: XDEBUG_OFF="yes"

before_install:
  # Mock mail service
  - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then sudo bash tests/bin/prepare.sh; fi

before_script:
  # Prepare Filesystem
  - mkdir -p ./build
  - mkdir -p ./build/logs
  - mkdir -p ./build/clover
  - mkdir -p ./resource

  # Install PHP Libs
  - composer self-update
  - composer update --optimize-autoloader

  # Disable xdebug PHP module
  - if [[ $XDEBUG_OFF = yes ]]; then phpenv config-rm xdebug.ini; fi;

script:
  # Full stack
  - composer manifest
  - composer autoload

  - composer prepare-wordpress
  - composer phpunit-wordpress

  - composer prepare-joomla
  - composer phpunit-joomla

  # Other tests
  - composer phpmd
  - composer phpcs
  - composer phpcpd
  - composer phploc

after_script:
  - composer coveralls
