language: php

services:
  - mysql

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0

before_script:
  - composer update-all

  # Prepare Joomla
  - vendor/bin/joomla site:create joomla --www="./resources" --mysql-login="root:" --mysql-host="127.0.0.1" --mysql-database=cms_joomla --verbose

  # Prepare Wordpress
  - mkdir -p ./resources/wordpress
  - mysql -e 'create database cms_wp;'
  - vendor/bin/wp core download --path=./resources/wordpress
  - vendor/bin/wp core config --path=./resources/wordpress --dbname=cms_wp --dbuser=root --dbhost="127.0.0.1"

  # Update env
  - phpenv rehash

script:
  - composer test

after_script:
  - composer coveralls

notifications:
  slack: jbzoo:lKYRTvAF36tRDfKTOK5zhFh9

